plugins {
  id 'java'
  id 'org.springframework.boot' version '3.5.14'
  id 'io.spring.dependency-management' version '1.1.7'
  id 'org.jetbrains.kotlin.jvm' version '2.2.21' apply false
}

group = 'com.github.retro_game'
version = '0.42.0'
description = 'Retro Game'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

dependencies {
  implementation project(':battle-engine')

  implementation 'com.google.guava:guava:33.4.8-jre'
  implementation 'io.hypersistence:hypersistence-utils-hibernate-63:3.15.2'
  implementation 'io.vavr:vavr:0.10.7'
  implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.4.0'
  implementation 'org.apache.commons:commons-lang3'
  implementation 'org.postgresql:postgresql'
  implementation 'org.springframework.boot:spring-boot-starter-aop'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-data-redis'
  implementation 'org.springframework.boot:spring-boot-starter-mail'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.session:spring-session-data-redis'
  implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'

  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.junit.vintage:junit-vintage-engine'
  testImplementation 'org.springframework.security:spring-security-test'
  testImplementation 'org.testcontainers:postgresql'
  testCompileOnly 'org.projectlombok:lombok'
  testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
  options.release = 21
}

tasks.named('jar') {
  enabled = false
}

springBoot {
  buildInfo()
}

tasks.named('test') {
  useJUnitPlatform()
  systemProperty 'retro-game.native-tests', System.getProperty('retro-game.native-tests', 'false')

  if (System.getProperty('retro-game.native-tests') == 'true') {
    dependsOn ':battle-engine:buildBattleEngine'
    systemProperty 'java.library.path', project(':battle-engine').layout.buildDirectory.dir('native').get().asFile.absolutePath
  }
}
