FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /retro-game-src
COPY . .
RUN \
  # Install packages needed to build the game.
  apk --no-cache add \
    cmake \
    g++ \
    make \
    musl-dev && \
  ./gradlew --no-daemon :battle-engine:buildBattleEngine :bootJar -x test && \
  rm -rf ~/.gradle

FROM eclipse-temurin:21-jre-alpine
WORKDIR /retro-game
COPY --from=0 /retro-game-src/battle-engine/build/native/libBattleEngine.so .
COPY --from=0 /retro-game-src/build/libs/retro-game-*.jar retro-game.jar
RUN apk --no-cache add postgresql-client
CMD ["java", "-Djava.library.path=.", "-jar", "retro-game.jar"]
